### ISSUE TITLE
Confused repo identity bloom42 vs z0mbie42

### ISSUE THREAD

**Issue by tv42** [z0mbie42/rz-go#14]
Your go.mod says github.com/bloom42/rz-go but github redirects that to https://github.com/z0mbie42/rz-go. Is the whole thing migrating over, should these import paths change, or what? This is quite confusing.

**Comment by z0mbie42** [comment]
Hi @tv42,

I apologize for the inconvenience, I will migrate this repository to GitLab (and fix the import path problem) in the next 2 days.

The new import path will be `gitlab.com/z0mbie42/rz-go`
