### ISSUE TITLE
Project Moved

### ISSUE THREAD

**Issue by runeimp** [z0mbie42/rz-go#22]
Please put a note in the README that states this project has moved to <https://gitlab.com/z0mbie42/rz-go>. Also, **STOP MOVING THE PROJECT AROUND WITHOUT NOTIFICATION**! First it was at <https://github.com/bloom42/rz-go>, then suddenly appeared at <https://github.com/z0mbie42/rz-go>, and (hopefully) finally moved to <https://gitlab.com/z0mbie42/rz-go>. Something I was only able to find by reading through closed issues at <https://github.com/z0mbie42/rz-go>. At the very least do _not_ close this issue so that others might have some hope of finding where the project has moved if the don't see the update on the README.

**Comment by z0mbie42** [comment]
Hi,

Sorry for not replying early.

Done in 6e9e14d.

I apologize but the repo is in maintenance mode, I do not have time to Add features etc..

I'll make it clear in the next few days
