### ISSUE TITLE
gomodule import pathing breaks existing golang/dep

### ISSUE THREAD

**Issue by jszwedko** [z0mbie42/rz-go#7]
This appears to be an is [an issue with `golang/dep`'s inability to handle import pathing that encodes the version](https://github.com/golang/dep/issues/1961) as you have here (`github.com/bloom42/rz-go/v2`) starting with `v2.4.0`.

The exact error it returns is `v2.4.2: "github.com/bloom42/rz-go" imports "github.com/bloom42/rz-go/v2/internal/json", which contains malformed code: no package exists at "github.com/bloom42/rz-go/v2/internal/json"`.

I realize that this isn't an issue with `rz-go`, but given that modules are still experimental and not yet widely adopted I was wondering if you'd be willing to maintain a `v2` branch that has the import paths not using the `/v2` suffix. I'm happy to open a PR for this if acceptable.

Thanks again for your work!

**Comment by z0mbie42** [comment]
Hi, as a non user of `dep`  (I use `go mod`)

**Comment by z0mbie42** [comment]
Hi, Thank you for the error report!

As a non user of `dep` (I use `go mod`, which fails if a module's path which version is superior to 1 does not start wit the version) I cannot maintain it myself, But I would be happy if you could PR.

To understand it's just creating a branch and changing all imports from `github.com/bloom42/rz-go/v2` to `github.com/bloom42/rz-go` ? 

And how the `dep` users would specify to use the `v2` branch ?

**Comment by jszwedko** [comment]
Apologies for the delayed response! Just getting back from vacation.

That's basically it. You can see the diff here: https://github.com/bloom42/rz-go/compare/master...jszwedko:v2?expand=1

`dep` users can then at least pin to the `v2` branch or a specific revision of this branch.

It would look something like:

```toml
[[constraint]]
  name = "github.com/bloom42/rz-go"
  revision = "8b60e7310d416b8fca9c6d41f932c84365cc3955"
```

Unfortunately the semantic version matching wouldn't work as tags would still be pointing to `master`, but I think this is a reasonable workaround until go modules become more mainstream.

**Comment by jszwedko** [comment]
Closing this as we switched to using Go modules and no longer have need of `dep` support. Thanks again for your work!
